import { fromJS } from 'immutable'
export const comments = fromJS([
  {
    "id":"5a588dd5dacf99164b5ddead",
    "author":"1",
    "text":"123",
    "parent_type":"Photo",
    "parent_id":"5a4fd7c7dacf9949a9ede35b",
    "comments":
      [
        {
          "id":"5a588ddddacf99164b5ddeae",
          "author":"er",
          "text":"fghf",
          "parent_type":"Comment",
          "parent_id":"5a588dd5dacf99164b5ddead",
          "comments":
            [
              {
                "id":"5a588ed1dacf99164b5ddeb3",
                "author":"rt",
                "text":"ewrtewr",
                "parent_type":"Comment",
                "parent_id":"5a588ddddacf99164b5ddeae",
                "comments":[]
              }
            ]
        },
        {
          "id":"5a589761dacf99226ebba828",
          "author":"tyd",
          "text":"ytdk",
          "parent_type":"Comment",
          "parent_id":"5a588dd5dacf99164b5ddead",
          "comments":[]
        }
      ]
  },
  {
    "id":"5a588e4ddacf99164b5ddeaf",
    "author":"dsfgf",
    "text":"gdhjg",
    "parent_type":"Photo",
    "parent_id":"5a4fd7c7dacf9949a9ede35b",
    "comments":
      [
        {
          "id":"5a588e54dacf99164b5ddeb0",
          "author":"fgdjh",
          "text":"ghj",
          "parent_type":"Comment",
          "parent_id":"5a588e4ddacf99164b5ddeaf",
          "comments":[]
        }
      ]
  }
])